# -*- coding: utf-8 -*-
"""tas_kagit_makas_ZEHRA_SULTAN_BAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODrlDf6ycEspjoFc7CGDbn1nCivx9-mH
"""

import random as r   ## random modülü import ediliyor

def tas_kagit_makas_ZEHRA_SULTAN_BAS() :
  ## oyun hakkında kullanıcıya bilgi veriliyor
  print("ROCK, PAPER AND SCISSOR GAME" '\n' "*******************")
  print("GAME RULES" '\n' '\n' )
  print("Hello there, first of all WELCOME!. In the Rock, Paper or Scissor's "
        "game,We want to get information to you some important rules" )
  print("Firstly, we talk about game mechanism. In this game played against"
        "the computer, each game consists of 6 rounds. You, as the player, "
        '\n'"start the game by choosing one of the 'Rock, Paper and Scissor' "
        "options. The computer then plays a move." '\n'
        "If we were to tell you which option is superior in the connections "
        "between Rock, Paper and Scissor:" '\n'
        "Rock-Paper ==> Paper" '\n' "Rock-Scissor ==> Rock" '\n'
        "Paper-Scissor ==> Scissor" '\n'
        "Lastly, There is most important rule. If you can get the point"
        " in the first two round, you win the game!" '\n'
        "GOOD LUCK!!!")

  options = ["Rock",
             "Paper",
             "Scissor"]    ##liste yapisiyla secenekler belirleniyor

  ## oyunun devam etmesi icin de seceneklerin bulundugu bir liste belirleniyor
  answer = ["Yes",
            "No"]

  user_win = 0         ## kullanici galibiyet sayaci
  comp_win = 0         ## bilgisayar galibiyet sayaci
  turn_num = 0         ## tur sayaci
  game_num = 0         ## oynanan oyun sayisi

  while True :

    ##kullanicinin  hareketinin ogrenilmesi
    user_answer = input("What is your move? Rock, Paper or Scissor...")

    """ bilgisayarin oyundaki seciminin alinmasi random modulunde bulunan
    choice() yapisiyla saglanmaktadir """

    comp_answer = r.choice(options)
    print("Computer answer is " + comp_answer)

    if user_answer.capitalize() in options:

      while True :

        ## oyunda secilen hamlelere gore sayaclardaki atamalarin yapilmasi
        if user_answer.capitalize() == "Rock" and  comp_answer == "Paper":
          comp_win += 1
          print(f"Score ==> {user_win} : {comp_win}")
          turn_num += 1
          if comp_win == 2 and turn_num == 2:
            print("GAME IS OVER!!")
            print("YOU LOSE... MAYBE NEXT TIME.")

            ## oyuncuya oyuna devam etmek isteyip istemediği sorulur
            do_or_die = input("Do you want to continue the game? Yes or No?")
            comp_answer2 = r.choice(answer)

            """bilgisayar ve kullanicinin cevaplarina gore oyunun devam edip
            etmeyecegi belirlenir"""

            if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              game_num += 1
              print(f"Round {game_num}! Game is beginning!!")
              user_win = 0
              comp_win = 0
              break

            elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            else:
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              game_num +=1
              print(f"Game number is {game_num}.")
              break

            break


          elif user_win == 2 and turn_num==2 :
            print("GAME IS OVER!!")
            print("YOU WINNN!!!!")

            do_or_die = input("Do you want to continue the game? Yes or No?")
            comp_answer2 = r.choice(answer)

            if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              game_num += 1
              print(f"Round {game_num}! Game is beginning!!")
              user_win = 0
              comp_win = 0
              break
            elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            else:
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              game_num +=1
              print(f"Game number is {game_num}.")
              break

            break
          else :
            print("Game still going!!")
            break


        elif user_answer.capitalize() == "Rock" and comp_answer == "Scissor" :
          user_win += 1
          print(f"Score ==> {user_win} : {comp_win}")
          turn_num += 1

          if comp_win == 2 and turn_num ==2 :
            print("GAME IS OVER!!")
            print("YOU LOSE... MAYBE NEXT TIME.")
            do_or_die = input("Do you want to continue the game? Yes or No?")
            comp_answer2 = r.choice(answer)

            if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
              game_num += 1
              print(f"Round {game_num}! Game is beginning!!")
              user_win = 0
              comp_win = 0
              break
            elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            else:
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              game_num +=1
              print(f"Game number is {game_num}.")
              break

            break


          elif user_win == 2 and turn_num==2 :
            print("GAME IS OVER!!")
            print("YOU WINNN!!!!")
            do_or_die = input("Do you want to continue the game? Yes or No?")
            comp_answer2 = r.choice(answer)

            if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
              game_num += 1
              print(f"Round {game_num}! Game is beginning!!")
              user_win = 0
              comp_win = 0
              break
            elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              break
            elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
              print("Computer answer is " + comp_answer2)
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              return False
            else:
              print("GAME IS OVER, SEE YOU NEXT TIME!")
              game_num +=1
              print(f"Game number is {game_num}.")
              break
            break

          else:
            print("Game still going!!")
            break



      ##<<<<<<<<<

        elif user_answer.capitalize() == "Paper" and comp_answer == "Rock" :
            user_win += 1
            print(f"Score ==> {user_win} : {comp_win}")
            turn_num += 1

            if comp_win == 2 and turn_num ==2 :
              print("GAME IS OVER!!")
              print("YOU LOSE... MAYBE NEXT TIME.")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break

            elif user_win == 2 and turn_num==2 :
              print("GAME IS OVER!!")
              print("YOU WINNN!!!!")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break
            else :
              print("Game still going!!")
              break

        elif user_answer.capitalize() == "Paper" and comp_answer == "Scissor" :
            user_win += 1
            print(f"Score ==> {user_win} : {comp_win}")
            turn_num += 1

            if comp_win == 2 and turn_num ==2 :
              print("GAME IS OVER!!")
              print("YOU LOSE... MAYBE NEXT TIME.")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break

            elif user_win == 2 and turn_num==2 :
              print("GAME IS OVER!!")
              print("YOU WINNN!!!!")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break
            else:
              print("Game still going!!")
              break

        elif user_answer.capitalize() == "Scissor" and comp_answer == "Rock" :
            user_win += 1
            print(f"Score ==> {user_win} : {comp_win}")
            turn_num += 1

            if comp_win == 2 and turn_num ==2 :
              print("GAME IS OVER!!")
              print("YOU LOSE... MAYBE NEXT TIME.")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break
            elif user_win == 2 and turn_num==2 :
              print("GAME IS OVER!!")
              print("YOU WINNN!!!!")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break

            else:
              print("Game still going!!")
              break

        elif user_answer.capitalize() == "Scissor" and comp_answer == "Paper" :
            user_win += 1
            print(f"Score ==> {user_win} : {comp_win}")
            turn_num += 1

            if comp_win == 2 and turn_num ==2 :
              print("GAME IS OVER!!")
              print("YOU LOSE... MAYBE NEXT TIME.")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break

            elif user_win == 2 and turn_num==2 :
              print("GAME IS OVER!!")
              print("YOU WINNN!!!!")
              do_or_die = input("Do you want to continue the game? Yes or No?")
              comp_answer2 = r.choice(answer)

              if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                game_num += 1
                print(f"Round {game_num}! Game is beginning!!")
                user_win = 0
                comp_win = 0
                break
              elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" and turn_num == 2 :
                print("Computer answer is " + comp_answer2)
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                break
              else:
                print("GAME IS OVER, SEE YOU NEXT TIME!")
                game_num +=1
                print(f"Game number is {game_num}.")
                break

              break

            else:
              print("Game still going!!")
              break

        else:
          print("You have no extra point.")
          print(f"Score ==> {user_win} : {comp_win}")
          turn_num +=1
          break

    else:
      print("Please, choose in options.")
      continue

    """ Oyun totalde 6 turdan olusmaktadir. Eger ustteki kosullar saglanmazsa
     oyun 6 tur surer. 6 turun sonunda kimin kazanip kazanmadigi durumlar bu
     kisimda belirlenmistir"""

    if comp_win >user_win and turn_num == 6 :
      print("GAME NUM IS LIMITED. GAME IS END. YOU LOSE!")

      do_or_die = input("Do you want to continue the game? Yes or No?")
      comp_answer2 = r.choice(answer)

      if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        game_num += 1
        print(f"Round {game_num}! Game is beginning!!")
        user_win = 0
        comp_win = 0
        continue
      elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      else:
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        game_num +=1
        print(f"Game number is {game_num}.")
        break

    elif comp_win < user_win and turn_num == 6 :
      print("GAME NUM IS LIMITED. GAME IS END. YOU WINN!")
      do_or_die = input("Do you want to continue the game? Yes or No?")
      comp_answer2 = r.choice(answer)

      if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        game_num += 1
        print(f"Round {game_num}! Game is beginning!!")
        continue
      elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      else:
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        game_num +=1
        print(f"Game number is {game_num}.")
        break

    elif user_win == comp_win and turn_num == 6 :
      print("DRAW !")
      do_or_die = input("Do you want to continue the game? Yes or No?")
      comp_answer2 = r.choice(answer)

      if do_or_die.capitalize() == "Yes" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        game_num += 1
        print(f"Round {game_num}! Game is beginning!!")
        user_win = 0
        comp_win = 0
        continue
      elif do_or_die.capitalize() == "No" and comp_answer2 == "Yes" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      elif do_or_die.capitalize() == "Yes" and comp_answer2 == "No" :
        print("Computer answer is " + comp_answer2)
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        break
      else:
        print("GAME IS OVER, SEE YOU NEXT TIME!")
        game_num +=1
        print(f"Game number is {game_num}.")
        break

    else :
        continue

## olusturulan metot cagirilir
tas_kagit_makas_ZEHRA_SULTAN_BAS()